version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - chromadb
      - ollama
    environment:
      OLLAMA_URL: "http://ollama:11434"
    restart: unless-stopped
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  chroma_data:
